### ISSUE TITLE
Google pixel 7a

### ISSUE THREAD

**Issue by WPHorhe** [legendsayantan/ShizuTools#10]
On my device I used your app do uninstall almost everything marked as green and I got from barely a day to 1d 6h beside the fact that I hotspot everyday to my PC on 5g 5ghz band and there is one service that I disabled which causes the app to close and disable the developer options the so I had no option to turn developer options back on and your app didn't work , fortunely I just performed a restart to the phone and everything worked fine and also the Google Play system update button does not work it takes me back when I click on it idk what broke it , the service that I was talking about is (Main Components , package: com.google.mainline.adservices) marked as recommend to uninstall.

**Comment by legendsayantan** [comment]
You can re-install uninstalled apps through the restore menu present in the debloater, if that's what you're looking for.

**Comment by WPHorhe** [comment]
Yes I know I just posted this so maybe you can add a note to that specific package if u understood what I said , do you know what might have Brooke the Google play system updates ?

**Comment by legendsayantan** [comment]
The data is fetched from [UAD Repo](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation). You should inform them about this behaviour, that way other apps like this one would be updated as well.
