### ISSUE TITLE
Bug: Using SoundMaster after selecting app there is no choice for audio output.

### ISSUE THREAD

**Issue by Ral60** [legendsayantan/ShizuTools#12]
![Screenshot_20240615-165613](https://github.com/legendsayantan/ShizuTools/assets/89457175/519671cd-d9e6-4b41-8a05-2982510991fd)

Device: Sony Xperia 5 II
OS: Android 12
App version: 1.4.2

**Comment by legendsayantan** [comment]
Looking into it. Do you have any earphones connected when it happens, or is it just the device speaker?

**Comment by legendsayantan** [comment]
If you can, try [this version](https://github.com/legendsayantan/ShizuTools/blob/master/app/release/app-release.apk) if the same issue occurs here as well.

**Comment by Ral60** [comment]
> Looking into it. Do you have any earphones connected when it happens, or is it just the device speaker?

It happens with earphones and device speaker.

**Comment by Ral60** [comment]
> If you can, try [this version](https://github.com/legendsayantan/ShizuTools/blob/master/app/release/app-release.apk) if the same issue occurs here as well.

It is working with this. Thanks for the quick response

**Comment by Ral60** [comment]
However the volume does not seem to change even though the sliders are moving. I have tried YT Revanced, PipePipe, Musicolet and Spotify.

**Comment by legendsayantan** [comment]
Have you hit the round "play" button at the top?

**Comment by legendsayantan** [comment]
SoundMaster does not work with Spotify, that I have deducted from testing. However, it should work on YouTube and others...

**Comment by Ral60** [comment]
> Have you hit the round "play" button at the top? After you do that, there should be a new notification that says "Soundmaster is controlling x apps, average latency is y"... Within 30 seconds

Yes it works after clicking "play" button. Sorry for the inconvenience I gave you.
