### ISSUE TITLE
IntentShell not visible 

### ISSUE THREAD

**Issue by anirov** [legendsayantan/ShizuTools#16]
When scrolling fully, the last block (IntentShell) is not displayed
![Screenshot_20240623235045](https://github.com/legendsayantan/ShizuTools/assets/81052204/90f5d8ce-45ee-43a6-905f-e2750a544ea8)
.....
Redmi Note, MIUI 12. Android 11
![Screenshot_20240623235909](https://github.com/legendsayantan/ShizuTools/assets/81052204/0afd92f1-6e5a-4fca-9791-31ce5de48f91)
P.S. 
command &key in Tasker or Macrodroid... It is unclear how to fill in the fields correctly. Help please.
![Screenshot_20240623235001](https://github.com/legendsayantan/ShizuTools/assets/81052204/58c6da7f-6751-4b4b-8ba1-1a82435bfafd)
![Screenshot_20240623234928](https://github.com/legendsayantan/ShizuTools/assets/81052204/0c8ebdf4-a195-4d82-9268-37bfc6c4dcf4)

**Comment by legendsayantan** [comment]
[Here](https://github.com/legendsayantan/ShizuTools/wiki/IntentShell) is a brief example of how to set up Macrodroid to be used with ShizuTools. For the intent shell hiding issue, should be fixed in v1.4.3 (releasing soon).
