### ISSUE TITLE
MixedAudio - Search?

### ISSUE THREAD

**Issue by w4t3r1ily** [legendsayantan/ShizuTools#18]
Do you think it'd be possible to add search option to MixedAudio? The way it lists the apps is neither alphabetical nor chronolohical, so it's bit fifficult to find the app I wanna mute. Snyway thanks for yoyr app, its very useful.

**Comment by legendsayantan** [comment]
I do plan to implement a filter mode like the debloater has, will try to get it done soon as I can.
