### ISSUE TITLE
App crashes every time I execute an adb command

### ISSUE THREAD

**Issue by Mujtaba0150** [legendsayantan/ShizuTools#2]
The app crashes every time I try running an adb shell command. I've tried this for multiple commands and am running Android 13 on a Samsung device with OneUI 5.1

**Comment by legendsayantan** [comment]
Thanks, the adb shell part still needs a lot of work and is actively being worked on.

**Comment by Mujtaba0150** [comment]
E/AndroidRuntime( 3771): Process: com.legendsayantan.adbtools, PID: 3771
E/AndroidRuntime( 3771): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.legendsayantan.adbtools/output.txt: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.lib.Utils$Companion.lastCommandOutput(Utils.kt:88)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.MainActivity.openShell$lambda$7(MainActivity.kt:67)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.MainActivity.$r8$lambda$HUbNbzAjCoWotCgHAIPXHu3tGN4(Unknown Source:0)
E/AndroidRuntime( 3771):        at com.legendsayantan.adbtools.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
E/WindowManager( 1449): win=Window{87a71e4 u0 com.legendsayantan.adbtools/com.legendsayantan.adbtools.MainActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.WindowState.onExitAnimationDone:5997 com.android.server.wm.WindowStateAnimator.onAnimationFinished:225 com.android.server.wm.WindowState.onAnimationFinished:6222 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:140 com.android.server.wm.SurfaceAnimator.$r8$lambda$lRxTVOJy8fX752UbrFno9INW9hE:0 com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda1.run:8

**Comment by Mujtaba0150** [comment]
I've also noticed that the app closes when I select the MixedAudio option. Here's the log for that:

E/AndroidRuntime( 4322): Process: com.legendsayantan.adbtools, PID: 4322
E/AndroidRuntime( 4322): java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.legendsayantan.adbtools/output.txt: open failed: ENOENT (No such file or directory)
E/AndroidRuntime( 4322):        at com.legendsayantan.adbtools.lib.Utils$Companion.lastCommandOutput(Utils.kt:88)
E/AndroidRuntime( 4322):        at com.legendsayantan.adbtools.MixedAudioActivity.reloadApps(MixedAudioActivity.kt:39)
E/AndroidRuntime( 4322):        at com.legendsayantan.adbtools.MixedAudioActivity.onCreate$lambda$0(MixedAudioActivity.kt:27)
E/AndroidRuntime( 4322):        at com.legendsayantan.adbtools.MixedAudioActivity.$r8$lambda$ffJ1Hu0qdhSzXuG9R_Gei9N-uj0(Unknown Source:0)
E/AndroidRuntime( 4322):        at com.legendsayantan.adbtools.MixedAudioActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
E/WindowManager( 1449): win=Window{3fb1660 u0 com.legendsayantan.adbtools/com.legendsayantan.adbtools.MainActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6539 com.android.server.wm.ActivityRecord.destroySurfaces:6520 com.android.server.wm.WindowState.onExitAnimationDone:5995 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2 java.util.ArrayList.forEach:1528 com.android.server.wm.ActivityRecord.onAnimationFinished:8607 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished:2
E/WindowManager( 1449): win=Window{1e0f3ae u0 com.legendsayantan.adbtools/com.legendsayantan.adbtools.MixedAudioActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6539 com.android.server.wm.ActivityRecord.destroySurfaces:6520 com.android.server.wm.WindowState.onExitAnimationDone:5995 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2 java.util.ArrayList.forEach:1528 com.android.server.wm.ActivityRecord.onAnimationFinished:8607 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished:2

**Comment by legendsayantan** [comment]
this issue should not occur anymore on the latest available apk file.
