### ISSUE TITLE
Sound master 

### ISSUE THREAD

**Issue by mintoya** [legendsayantan/ShizuTools#22]
For me, nothing come up when soundmaster is opened, specifically on 1.4.3, however a very limited list of apps appears on 1.4.2, the same list opens in 1.4.1, but then the app instantly crashes

**Comment by legendsayantan** [comment]
In the last version 1.4.3, for the apps to appear you have to wait for a couple moments for ShizuTools to collect and arrange the list of apps. In the older version 1.4.2, The list starts small but should have grown after moments, for the same reason mentioned. However, the earlier versions has some bugs and crashing issues so i would not recommend using them.

**Comment by mintoya** [comment]
> In the last version 1.4.3, for the apps to appear you have to wait for a couple moments for ShizuTools to collect and arrange the list of apps. In the older version 1.4.2, The list starts small but should have grown after moments, for the same reason mentioned. However, the earlier versions has some bugs and crashing issues so i would not recommend using them. 

Upon testing it on my non rooted Galaxy note 10 on android 13, it works perfectly(I use a rooted nothing cmf phone on android 14) so it seems to be my device effecting it
