### ISSUE TITLE
ERROR: sh: adb: inaccessible or not found

### ISSUE THREAD

**Issue by Software27425** [legendsayantan/ShizuTools#29]
I'm not sure what I'm doing wrong, but I remember a few months ago, I used LocalShell to give Tasker Write Secure Settings, and it worked fine then.

https://tasker.joaoapps.com/userguide/en/help/ah_secure_setting_grant.html

I gave it another try today, have Shizuku running, gave Shizutools authorization, made sure all apps have unrestricted battery usage, and wireless debugging is paired and connected, and now,

adb shell pm grant net.dinglisch.android.taskerm android.permission.WRITE_SECURE_SETTINGS

^ This isn't working for me. I get "ERROR: sh: adb: inaccessible or not found"

Am I doing something wrong? (I'm on Android 14.)

**Comment by legendsayantan** [comment]
You should not include the "adb shell" part.

**Comment by Software27425** [comment]
It worked now. Thank you!

**Comment by Software27425** [comment]
It worked now. Thank you!
