### ISSUE TITLE
Closed problem 

### ISSUE THREAD

**Issue by Vivekz0o** [legendsayantan/ShizuTools#32]
After few minutes sound master auto closed and 
doesn't  hear the sound.

**Comment by Ermageeerd** [comment]
Rename this, the name is a bit confusing and may lead them to close the issue.

**Comment by legendsayantan** [comment]
@Vivekz0o When it happened, did you check if shizuku was still running after that? If if was, providing logs would be helpful to debug this crash.

**Comment by legendsayantan** [comment]
Closed for inactivity.
