### ISSUE TITLE
Disabling Android Easter Egg stops CA Certificates from installing

### ISSUE THREAD

**Issue by GlitchHopAnonymous** [legendsayantan/ShizuTools#42]
I spent hours enabling & disabling settings until I finally enabled this & was allowed to install a CA Cert. I am using a Samsung Tab S8 Ultra w/ Android 14.

**Comment by legendsayantan** [comment]
Report about this problem [here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues), so every single software using their debloat list can benefit from it.
