### ISSUE TITLE
Unable to revert to basic audio functions

### ISSUE THREAD

**Issue by riakai** [legendsayantan/ShizuTools#47]
Hi there--I tried using ShizuTools for a while but found it wasn't usable for my purpose (namely trying to override spotify's auto-pause when watching/listening to other things). Now that I'm trying to remove it, however, I'm having trouble getting vanilla audio behavior to function.

When uninstalling ShizuTools, all audio outputs no longer function--instead just producing a periodic 'click' from the speakers & the bluetooth earbuds. When reinstalling it & using SoundMaster or MixedAudio again, audio resumes as normal.

**Comment by riakai** [comment]
Ah, naturally, as soon as I posted an issue I managed to noodle around enough to figure it out. Apologies.

**Comment by Rayrsn** [comment]
Hi, how did you fix this? currently facing the same problem
