### ISSUE TITLE
Does LookBack only work on debug builds?

### ISSUE THREAD

**Issue by e-t-l** [legendsayantan/ShizuTools#6]
LookBack uses the `install -d` command, which I believe only works on debug apk builds. And when I tried downgrading an app to a previous apk, it didn't work. LookBack kept showing a message about "adb restrictions in developer options." I don't know what that means but Shizuku is already unning and connected. LookBack won't proceed past xhoosing an apk in the file picker dialog.

**Comment by legendsayantan** [comment]
It is not limited to debug builds. It's most likely that there are additional adb restrictions added by your device manufacturer, like "Permission monitoring" toggle found in Oppo roms, or "usb debugging security settings" toggle found in Xiaomi roms. You just need to find these rom-specific implementation in developer options and configure them in a way that there are no restrictions.

**Comment by dmytrovoytko** [comment]
Hi! I have similar situation - nothing (visible) happens after choosing **any** APK. Both USB debugging options are set On in developer options ![IMG_20240619_065958.jpg](https://github.com/legendsayantan/ShizuTools/assets/17794339/769875a3-b175-434a-9a0d-edd025175860)

What else should I check?

Xiaomi Redmi Note 8T, Android 9

**Comment by dmytrovoytko** [comment]
Similar behavior (nothing visible happens after choosing any APK) on another device - tablet (Android 9, no Google).
