### ISSUE TITLE
(Suggestion) Add the option of muting apps

### ISSUE THREAD

**Issue by w4t3r1ily** [legendsayantan/ShizuTools#8]
By now I'm using the ADB shell commands

`cmd appops set com.APPNAME TAKE_AUDIO_FOCUS ignore 

cmd appops set com.APPNAME PLAY_AUDIO deny`

To get rid off sounds in app, but it'd be nice if it was an intuitive option.

**Comment by legendsayantan** [comment]
That is a perfect suggestion, I'll make sure to include it in :)

**Comment by w4t3r1ily** [comment]
> That is an excellent suggestion, I'll make sure to include it in :)

Thank you
