### ISSUE TITLE
Please make the volume setting for each application

### ISSUE THREAD

**Issue by Beshardis** [legendsayantan/ShizuTools#9]
Please make the volume setting for each application. I do not know if it is possible or not, but I would really like to. For the sake of the audio mixer and I use this application, I am very grateful to you!
If there is an opportunity, it would be interesting to see the entire audio mix in the form of a volume slider so that it runs instead of the usual one.
My Concept is where you can mix only a few applications:
![Picsart_24-05-29_15-51-30-729](https://github.com/legendsayantan/ShizuTools/assets/171149808/fb1d89ec-f4ba-428e-a670-ef18cd3c40c5)
![Picsart_24-05-29_16-11-42-430](https://github.com/legendsayantan/ShizuTools/assets/171149808/a4ca7949-bf85-42d0-818f-608adab5bec7)

**Comment by legendsayantan** [comment]
According to my recent research... that is not consistently doable without root. However, I did come up with a workaround that can give you different volume levels on two different sets of apps. If you want to try it out while I perform more tests, [Here is an apk](https://github.com/legendsayantan/ShizuTools/blob/volumeplus/app/release/app-release.apk).

**Comment by Beshardis** [comment]
There is no root, since I have a Huawei tablet, I would really like to. At least a mini equalizer is for the volume of different applications. In general, there are such applications, but they are not able to change the volume without amplifying, and you want a strong understatement, almost to zero.

**Comment by Beshardis** [comment]
Thank you for giving hope for the prosperity of Android Capabilities. And thanks in general.

**Comment by Beshardis** [comment]
Спасибо Вам большое!!

**Comment by legendsayantan** [comment]
I just stumbled across something, and it seems somewhat plausible to give each apps its own volume slider! Please stay tuned for further updates.

**Comment by legendsayantan** [comment]
The latest update introduces SoundMaster, the ablility to control individual app volumes! Please check it [Here](https://github.com/legendsayantan/ShizuTools/releases/tag/v1.4.0)
